using System.Runtime.InteropServices.WindowsRuntime;

namespace SnelStart.B2B.Client.Operations
{
    /// <summary>
    /// Een enumeratie van grootboekfuncties.
    /// </summary>
    public enum GrootboekFunctieModel
    {
        Diversen,
        DagboekKas,
        DagboekBank,
        DagboekGiro,
        DagboekVerkoop,
        DagboekInkoop,
        DagboekMemoriaal,
        DagboekBalans,
        VerkopenOmzetOnbelastVerlegd,
        VerkopenOmzetLaag,
        VerkopenOmzetHoog,
        VerkopenOmzetOverig,
        VerkopenBtwVrij,
        BtwAfteDragenLaag,
        BtwAfTeDragenHoog,
        BtwAfTeDragenOverig,
        BtwAfTeDragenVerlegdVerkopen,
        BtwTeVorderenVerlegd,
        BtwAfteDragenLaagGlobalisatie,
        BtwAfTeDragenHoogGlobalisatie,
        BtwAfTeDragenOverigGlobalisatie,
        InkopenKostenAlleBtwTarieven,
        InkopenKostenLaag,
        InkopenKostenHoog,
        InkopenKostenOverig,
        InkopenVraagPosten,
        BtwTeVorderenLaag,
        BtwTeVorderenHoog,
        BtwTeVorderenOverig,
        BtwAfTeDragenVerlegdInkopen,
        BtwTeVorderenVerlegdInkopen,
        InkopenImportBinnenEUlaag,
        InkopenImportBinnenEUhoog,
        InkopenImportBinnenEUoverig,
        InkopenImportBuitenEUlaag,
        InkopenImportBuitenEUhoog,
        InkopenImportBuitenEUoverig,
        VerkopenExportBinnenEU,
        VerkopenExportBuitenEU,
        OninbareVorderingen,
        HerrekeningCorrecties,
        InstallatieTeleverkoopBinnenEUgeen,
        BpmVerkopen,
        BpmInkopen,
        BpmVoorraad,
        DienstverleningBinnenEU,
        VerkoopGlobalisatieLaag,
        VerkoopGlobalisatieHoog,
        VerkoopGlobalisatieOverig,
        InkoopGlobalisatieLaag,
        InkoopGlobalisatieHoog,
        InkoopGlobalisatieOverig,
        BtwGlobalisatie,
        KredietbeperkingVerkopen,
        KredietbeperkingInkopen,
        Betalingskorting,
        TussenrekeningBetalingen,
        OnbekendeBetalingen,
        Kruisposten,
        ContanteBetaling,
        ElectronischeBetaling,
        Winstboeking
    }
}
